### PR TITLE
SunCodeFlower team creation

### PR DESCRIPTION
**Pull request by oshka**
@dunphyben ! Olha and Itsik have created the team  - SunCodeFlower

### CODE REVIEW

**Comment by dunphyben** [comment]
Please do not delete the example entry. 

You should not be deleting any code from that template. You should only add your team's information to the bottom based on that template.

**Comment by oshka** [comment]
I have restored example entry

**Comment by sigu** [comment]
@oshka maybe you havent noticed but this has Conflicts, please resolve them first so collaborators can merge it. If you need help on that let me know

**Comment by oshka** [comment]
@dunphyben ! Benjamin Dunphy, why there are no our team (SunCodeFlower)  in teams.md
 file? How can you add us there?

**Pull request merged**
